dirs:
  raw_data: raw_data
  processed_data: processed_data
  schemas: schemas

constants:
  ISO3: YEM
  ISO2: YE
  crs: EPSG:2090
  crs_general: EPSG:4326
  altitude_light_deg: 315.0
  azimuth_light_deg: 45.0


# EXTRACT
world:
  hdx_cod:
    global_seaports:
      address: 'world-port-index'
      filename: 'world_port_index.zip'
  gadm:
    url: 'https://biogeo.ucdavis.edu/data/gadm3.6/gpkg/gadm36_{ISO3}_gpkg.zip'
  geoboundaries:
    url: https://www.geoboundaries.org/gbRequest.html?ISO=ALL&ADM=ADM0&TYP=SSCGS
  ourairports:
    url: 'https://ourairportapi.com/airports-in/'
countries:
  yemen:
    hdx_cod:
      adm:
        address: 'yemen-admin-boundaries'
        filename: 'yem_adm_govyem_cso_ochayemen_20191002_GPKG.zip'
      roads:
        address: 'yemen-roads'
        filename: 'ymn-roads.zip'
      river:
        address: 'yemen-water-bodies'
        filename: 'wadies.zip'
      seaport:
        address: 'yemen-ports'
        filename: 'ymn-seaport.zip'

#   Can be generated from world:gadm:url
    gadm:
      url: 'https://biogeo.ucdavis.edu/data/gadm3.6/gpkg/gadm36_YEM_gpkg.zip'

#   Todo srtm, ourairports, wfp_airports, osm
# Todo TRANSFORM



geoboundaries:
  # https://www.geoboundaries.org/api.html
  url: 'https://www.geoboundaries.org/gbRequest.html'
  typ: 'TYP=SSCGS'
  all: 'ISO=ALL&ADM=ADM0&TYP=SSCGS'
  isofield: 'shapeISO'
  subfolder: 'geoboundaries'
  raw: 'geobnd_'    # The Extract process will ammend the admX level and .zip
  downloadURL_api_key: 'downloadURL'
  boundaryType_api_key: 'boundaryType'
  adm0:
    raw: 'geobnd_adm0.zip'
    unzip: 'geobnd_adm0'
    processed: 'yem_admn_ad0_py_s0_geobnd_pp.shp'
  adm1:
    raw: 'geobnd_adm1.zip'
    processed: 'yem_admn_ad1_py_s0_geobnd_pp.shp'
  adm2:
    raw: 'geobnd_adm2.zip'
    processed: 'yem_admn_ad2_py_s0_geobnd_pp.shp'
