solids:
  extract_admin_cod:
    inputs:
      hdx_address:
        value: yemen-admin-boundaries
      hdx_filename:
        value: yem_adm_govyem_cso_ochayemen_20191002_GPKG.zip
  read_in_admin_cod:
    config:
      max_admin_level: 3
