constants:
  ISO3: YEM
  ISO2: YE

hdx_cod:
  adm:
    address: yemen-admin-boundaries
    filename: yem_adm_govyem_cso_ochayemen_20191002_GPKG.zip
  roads:
    address: yemen-roads
    filename: ymn-roads.zip

adm0:
  cod:
    column_names:
      name_en: admin0Name_en
      pcode: pcode
adm1:
  schema: admin1_affected_area_py.yml
  cod:
    column_names:
      name_en: admin1Name_en
      pcode: pcode
      par_pcode: par_pcode

